name: Rodar e testar aplicação

on: 
    push:
        branches:
            - main
    schedule:
        - cron: '00 18 * * 6' # Além do push, o código roda todo sábado as 18h

jobs:
    Rodar:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '6.0.x'
            - name: Instalar dependencias
              run: dotnet restore **/*.csproj
            - name: Build
              run: dotnet build **/*.csproj --no-restore
            - name: Teste
              run: dotnet test **/*.csproj
            - name: Roda a aplicação
              run: |
                nohup dotnet run --project github4women/github4women.csproj &
                sleep 10
            - name: Verifica se a aplicação está rodando
              run: |
                if pgrep -f 'dotnet'; then
                  echo "Aplicação no ar";
                else
                  echo "Erro na aplicação." >&2;
                  exit 1;
                fi
